### ISSUE TITLE
一个小请求

### ISSUE THREAD

**Issue by yihui** [daijiang/website_hugo_source#1]
尽管我还没正式对外通知，但我在计划近期启动一个庞大的工程：让每一个 R 用户都有自己的网站。这个工程的名称就是 rbind.io。在启动初期，我需要一些样本来做示范。因为你的网站已经基本成型，所以我请求你把这个库转移给 rbind 账号，我会在那边加你为管理员，转移之后不会给你带来任何障碍，只是把你的库陈列在 https://github.com/rbind/ 下面而已。不知你意下如何。谢谢！

**Comment by daijiang** [comment]
绝对没有问题！告诉我应该怎么弄吧。

**Comment by yihui** [comment]
很简单：https://github.com/daijiang/website_hugo_source/settings 到下面 Transfer Ownership 中，把这个库转移给 rbind。

**Comment by daijiang** [comment]
I do not have permission to crate a repository there yet... Add me as a member?

**Comment by yihui** [comment]
哦，对，这确实是个问题。这样，你在你的库里添加一个源，然后把库推过去就好了：

```bash
git remote add rbind git@github.com:rbind/daijiang.git
git push -u rbind master
```

然后在 Netlify 里更改一下网站的 Github 库来源（选 rbind 这边的库）。如果能编译成功，那么你自己这边的库就可以删掉了。

**Comment by daijiang** [comment]
搞定，睡觉，睡觉。😃

**Comment by yihui** [comment]
完美。谢谢。这里的库就可以拆了，以后就更新 rbind 那边的库就够了。
